trigger: none

pool: $(poolName)

variables:
  buildConfiguration: 'Release'
  projectPath: './functions.csproj'

stages:
- stage: Build
  jobs:  
  - job: Build
    displayName: Build and publish solution
    steps:
    - task: UseDotNet@2      
      inputs:
        packageType: 'sdk'
        version: '3.x'
      displayName: 'Use .NET Core SDK 3.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(projectPath)'
      displayName: 'Restore NuGet packages'
 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(projectPath)'
      displayName: 'Build solution'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
      displayName: 'Publish solution'
      
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(armServiceConnection)
        appType: 'functionAppLinux'
        appName: $(functionAppName)
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      displayName: Deploy Azure Function