AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'apim-cs5'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apim-wus2-5'
VMAZDEVOPS_USERNAME: 'adoagent'
VMAZDEVOPS_PW: 'dN~bH9UG'
AZDEVOPS_ACCT: 'https://dev.azure.com/cykreng/'