AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'apim-cs6'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apim-wus2-7'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://dev.azure.com/cykreng/'
CICD_AGENT_TYPE: 'azuredevops'