name: 'Terraform ES-APIM Deploy'
 
on:
  push:
    branches:
      - none
    paths: 
      # - '**/*.tf'
      # - '**/*.tfvars'
  
  pull_request:
    paths:
      # - '**/*.tf'
      # - '**/*.tfvars'
 
  workflow_dispatch: 
 
jobs:
  deploy_azure:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./reference-implementations/AppGW-IAPIM-Func/terraform 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
       #Authenticate using service principal
      - name: Run Az Login 
        run: az login --service-principal -u ${{secrets.client_id}} -p ${{secrets.client_secret}} --tenant ${{secrets.tenant_id}}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -lock=false
        continue-on-error: false

      # [Placeholder] Outputs comment on the pull request:

     
